from django.urls import path
from auth_app.views import (
    RegisterView,
    LoginView,
    LogoutView,
    ProfileView,
    ProfileUpdateView,
    CheckAuthView,
    AvatarUploadView,
    SaveQuizAttemptView,
    GetHistoryView,
    GetHistoryDetailView,
    GetQuizHistoryByIdView,
    GetCategoryPerformanceView,
    GetUserStreakView,
    GetUserXPView,
    CreateUserQuizView,
    GetUserCreatedQuizzesView,
    GetUserAchievementsView,
    GetUserStatsView,
    RequestPasswordResetView,
    ResetPasswordView,
    GoogleSignInView,
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('google-signin/', GoogleSignInView.as_view(), name='google-signin'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='profile-update'),
    path('profile/avatar/', AvatarUploadView.as_view(), name='avatar-upload'),
    path('check/', CheckAuthView.as_view(), name='check-auth'),
    path('quiz/attempt/save/', SaveQuizAttemptView.as_view(), name='save-quiz-attempt'),
    path('quiz/history/', GetHistoryView.as_view(), name='quiz-history'),
    path('quiz/history/summary/', GetHistoryDetailView.as_view(), name='history-summary'),
    path('quiz/history/<int:attempt_id>/', GetQuizHistoryByIdView.as_view(), name='quiz-history-detail'),
    path('quiz/category-performance/', GetCategoryPerformanceView.as_view(), name='category-performance'),
    path('streak/', GetUserStreakView.as_view(), name='user-streak'),
    path('xp/', GetUserXPView.as_view(), name='user-xp'),
    path('quiz/create/', CreateUserQuizView.as_view(), name='create-user-quiz'),
    path('quiz/my-quizzes/', GetUserCreatedQuizzesView.as_view(), name='my-created-quizzes'),
    path('achievements/', GetUserAchievementsView.as_view(), name='user-achievements'),
    path('stats/comprehensive/', GetUserStatsView.as_view(), name='comprehensive-stats'),
    path('password-reset/request/', RequestPasswordResetView.as_view(), name='password-reset-request'),
    path('password-reset/confirm/', ResetPasswordView.as_view(), name='password-reset-confirm'),
]
