# Generated by Django 4.2.7 on 2025-11-27 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of login attempt')),
                ('email', models.EmailField(help_text='Email attempting to login', max_length=254)),
                ('success', models.BooleanField(default=False, help_text='Whether login was successful')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'indexes': [models.Index(fields=['ip_address', 'attempted_at'], name='auth_app_lo_ip_addr_c5f3e6_idx'), models.Index(fields=['email', 'attempted_at'], name='auth_app_lo_email_74db97_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text="User's full name", max_length=255)),
                ('avatar', models.URLField(blank=True, help_text="URL to user's avatar image", null=True)),
                ('avatar_file', models.FileField(blank=True, help_text='Uploaded avatar file', null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, help_text='User biography', null=True)),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='Store user preferences as JSON')),
                ('last_active', models.DateTimeField(auto_now=True, help_text='Last activity timestamp')),
                ('last_login', models.DateTimeField(blank=True, help_text='Last login timestamp', null=True)),
                ('email_verified', models.BooleanField(default=False, help_text='Email verification status')),
                ('email_verification_token', models.CharField(blank=True, max_length=255, null=True)),
                ('email_verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether account is active')),
                ('session_timeout_minutes', models.IntegerField(default=30, help_text='Session timeout in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'indexes': [models.Index(fields=['user', 'email_verified'], name='auth_app_us_user_id_1cdc41_idx'), models.Index(fields=['last_active'], name='auth_app_us_last_ac_6b2caf_idx'), models.Index(fields=['is_active'], name='auth_app_us_is_acti_6275b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Unique reset token', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Token expiration time')),
                ('is_used', models.BooleanField(default=False, help_text='Whether token has been used')),
                ('used_at', models.DateTimeField(blank=True, help_text='When token was used', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset',
                'verbose_name_plural': 'Password Resets',
                'indexes': [models.Index(fields=['token', 'is_used'], name='auth_app_pa_token_d54501_idx'), models.Index(fields=['user', 'expires_at'], name='auth_app_pa_user_id_020f25_idx')],
            },
        ),
    ]
