# Generated by Django 4.2.7 on 2025-12-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_userprofile_current_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='xp_score',
            field=models.IntegerField(default=0, help_text='Total experience points earned'),
        ),
    ]
