# Generated by Django 4.2.7 on 2025-12-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_userprofile_xp_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_quizzes',
            field=models.JSONField(blank=True, default=list, help_text='List of quiz_ids created by this user'),
        ),
    ]
