# Generated by Django 4.2.7 on 2025-12-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_userprofile_created_quizzes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_quizzes',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_quiz_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of quiz IDs created by this user'),
        ),
    ]
