# Generated by Django 4.2.7 on 2025-12-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_remove_userprofile_created_quizzes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='average_score',
            field=models.FloatField(default=0.0, help_text='Average score across all quizzes (percentage 0-100)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_correct_answers',
            field=models.IntegerField(default=0, help_text='Total number of questions answered correctly'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_questions_answered',
            field=models.IntegerField(default=0, help_text='Total number of questions answered in quizzes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_quizzes_attended',
            field=models.IntegerField(default=0, help_text='Total number of quizzes attended'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_time_spent_seconds',
            field=models.IntegerField(default=0, help_text='Total time spent in quizzes in seconds'),
        ),
    ]
