# Generated by Django 4.2.7 on 2025-12-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_userprofile_average_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fast_paced_points',
            field=models.IntegerField(default=0, help_text='XP earned from fast-paced quizzes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='time_based_points',
            field=models.IntegerField(default=0, help_text='XP earned from time-based quizzes'),
        ),
    ]
