# Generated by Django 4.2.7 on 2025-12-23 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_userprofile_fast_paced_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_weekly_reset',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Last time weekly XP was reset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weekly_xp',
            field=models.IntegerField(default=0, help_text='XP earned this week'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['weekly_xp'], name='auth_app_us_weekly__666c1a_idx'),
        ),
    ]
