# Generated by Django 4.2.7 on 2025-11-27 17:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category_type', models.CharField(choices=[('academic', 'Academic'), ('entertainment', 'Entertainment'), ('general_knowledge', 'General Knowledge')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='UserScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quizzes', models.IntegerField(default=0)),
                ('total_questions_answered', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('best_score', models.IntegerField(default=0)),
                ('worst_score', models.IntegerField(default=0)),
                ('last_quiz_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Score History',
                'verbose_name_plural': 'User Score Histories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='quiz_app.category')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('completed_questions', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired'), ('abandoned', 'Abandoned')], db_index=True, default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('metadata', models.TextField(default='{}', help_text='JSON field for additional metadata')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_sessions', to='quiz_app.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_sessions', to='quiz_app.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Session',
                'verbose_name_plural': 'Quiz Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.TextField(default='[]', help_text='JSON array of answer options')),
                ('correct_answer', models.CharField(max_length=500)),
                ('user_answer', models.CharField(blank=True, max_length=500, null=True)),
                ('is_correct', models.BooleanField(db_index=True, default=False)),
                ('ai_metadata', models.TextField(default='{}', help_text='JSON metadata from AI generation')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('quiz_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_app.quizsession')),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz Questions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quizzes_taken', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('total_users', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='quiz_app.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='quiz_app.subcategory')),
            ],
            options={
                'verbose_name': 'Category Statistics',
                'verbose_name_plural': 'Category Statistics',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='quiz_app_ca_slug_75e5cb_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_type'], name='quiz_app_ca_categor_c61454_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['created_at'], name='quiz_app_ca_created_f0458d_idx'),
        ),
        migrations.AddIndex(
            model_name='userscorehistory',
            index=models.Index(fields=['average_score'], name='quiz_app_us_average_8c6278_idx'),
        ),
        migrations.AddIndex(
            model_name='userscorehistory',
            index=models.Index(fields=['best_score'], name='quiz_app_us_best_sc_a82759_idx'),
        ),
        migrations.AddIndex(
            model_name='userscorehistory',
            index=models.Index(fields=['last_updated'], name='quiz_app_us_last_up_bbe7a3_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['parent_category', 'slug'], name='quiz_app_su_parent__0aeba4_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['difficulty_level'], name='quiz_app_su_difficu_589b47_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['created_at'], name='quiz_app_su_created_38c13f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('parent_category', 'slug')},
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['user', 'status'], name='quiz_app_qu_user_id_8f15d3_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['category', 'subcategory'], name='quiz_app_qu_categor_90cac7_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['started_at'], name='quiz_app_qu_started_d860c7_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['completed_at'], name='quiz_app_qu_complet_f4af28_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['user', 'started_at'], name='quiz_app_qu_user_id_710d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['quiz_session', 'is_correct'], name='quiz_app_qu_quiz_se_5362ca_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['created_at'], name='quiz_app_qu_created_d50b04_idx'),
        ),
        migrations.AddIndex(
            model_name='categorystatistics',
            index=models.Index(fields=['category', 'subcategory'], name='quiz_app_ca_categor_295017_idx'),
        ),
        migrations.AddIndex(
            model_name='categorystatistics',
            index=models.Index(fields=['average_score'], name='quiz_app_ca_average_3baf0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categorystatistics',
            unique_together={('category', 'subcategory')},
        ),
    ]
