# Generated by Django 4.2.7 on 2025-11-30 17:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.CharField(db_index=True, help_text='5-digit unique quiz ID', max_length=5, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(help_text='Interest or topic of the quiz', max_length=255)),
                ('difficulty_level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Mixed', 'Mixed')], max_length=20)),
                ('image_link', models.URLField(blank=True, null=True)),
                ('num_questions', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_minutes', models.IntegerField(help_text='Quiz duration in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Generated Quiz',
                'verbose_name_plural': 'Generated Quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempted_by', to='quiz_app.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz History',
                'verbose_name_plural': 'Quiz Histories',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField(help_text='List of options')),
                ('correct_answer', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_app.quiz')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
