# Generated by Django 4.2.7 on 2025-11-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_quiz_quizhistory_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizhistory',
            name='user_answers',
            field=models.JSONField(default=list, help_text='List of user answers with correctness'),
        ),
    ]
