# Generated by Django 4.2.7 on 2025-11-30 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_quizhistory_user_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_mock',
            field=models.BooleanField(default=False, help_text='If True, this is a pre-defined mock quiz'),
        ),
        migrations.AddField(
            model_name='quizhistory',
            name='questions',
            field=models.JSONField(default=list, help_text='List of questions generated for this attempt'),
        ),
        migrations.AddField(
            model_name='quizhistory',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizhistory',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizhistory',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
