# Generated by Django 4.2.7 on 2025-12-12 17:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0004_quiz_is_mock_quizhistory_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata (hints, tags, explanations)'),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default='', help_text='Question text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.CharField(blank=True, db_index=True, help_text='Quiz category (e.g., Mathematics, Science)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='duration_seconds',
            field=models.IntegerField(blank=True, help_text='Quiz duration in seconds', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='quiz',
            name='level',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('mixed', 'Mixed')], db_index=True, help_text='Difficulty level', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(help_text='Correct answer - must match one of the options', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(help_text='List of 4 options'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, help_text='Question order in quiz (1-based)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, help_text='Question text (legacy)', null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('mixed', 'Mixed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Quiz duration in minutes (legacy)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz', 'order'], name='quiz_app_qu_quiz_id_d017bf_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['quiz_id'], name='quiz_app_qu_quiz_id_dc9c89_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['category'], name='quiz_app_qu_categor_0c394d_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['level'], name='quiz_app_qu_level_2c1395_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['created_at'], name='quiz_app_qu_created_e514a2_idx'),
        ),
    ]
