# Generated by Django 4.2.7 on 2025-12-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_question_metadata_question_text_quiz_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_id',
            field=models.CharField(db_index=True, help_text='Unique quiz ID', max_length=20, unique=True),
        ),
    ]
