# Generated by Django 4.2.7 on 2025-12-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_alter_quiz_quiz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizhistory',
            name='quiz_type',
            field=models.CharField(choices=[('fast-paced', 'Fast Paced'), ('time-based', 'Time Based'), ('learning-based', 'Learning Based')], default='time-based', help_text='Quiz mode: fast-paced, time-based, or learning-based', max_length=20),
        ),
    ]
