# Generated by Django 4.2.7 on 2025-12-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_quizhistory_quiz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='language',
            field=models.CharField(default='English', help_text='Language of the quiz', max_length=50),
        ),
    ]
