# Generated by Django 4.2.7 on 2025-12-20 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0008_quiz_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('buzzer', 'Buzzer Mode'), ('lightning', 'Lightning Round'), ('scramble', 'Word Scramble'), ('two_truths', 'Two Truths One Lie')], db_index=True, max_length=50)),
                ('date', models.DateField(db_index=True, help_text='Date this activity is scheduled for')),
                ('title', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Activity',
                'verbose_name_plural': 'Daily Activities',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('lobby', 'Lobby'), ('active', 'Active'), ('finished', 'Finished')], default='lobby', max_length=20)),
                ('current_question_index', models.IntegerField(default=0)),
                ('state', models.JSONField(default=dict, help_text='Current game state (timer, active flags)')),
                ('join_code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='language',
        ),
        migrations.CreateModel(
            name='PlayerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='quiz_app.gamesession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='played_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gamesession',
            name='quiz_source',
            field=models.ForeignKey(blank=True, help_text='Optional link to a pre-built quiz', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_app.quiz'),
        ),
        migrations.CreateModel(
            name='ActivityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(help_text="Flexible content: {question: '...', options: [], answer: '...'}")),
                ('correct_answer', models.CharField(max_length=500)),
                ('points', models.IntegerField(default=10)),
                ('order', models.IntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_app.activity')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['date', 'type'], name='quiz_app_ac_date_ccd0ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('type', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='playersession',
            unique_together={('game_session', 'user')},
        ),
    ]
