# Generated by Django 4.2.7 on 2025-12-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0010_useractivityattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playersession',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playersession',
            name='xp_earned',
            field=models.IntegerField(default=0),
        ),
    ]
