# Generated by Django 4.2.7 on 2025-12-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0011_gamesession_completed_at_playersession_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='language',
            field=models.CharField(default='English', help_text='Language of the quiz content', max_length=50),
        ),
    ]
